
# problem : Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be : 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

print ('problem 2 ')
f1 = 1
f2 = 2
fandf = 0
count = 0
output = 0
maxval = 100

while fandf < maxval :
    print (fandf)
    count = count + 1
    fandf = f1 + f2
    f1 = f2
    f2 = fandf
    if fandf%2 == 0 and fandf < maxval :
        print ('yea',fandf)
        output = output + fandf
print(output,'is the answer for problem 2')
